#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

# mod "maestrodev/rvm"
mod "jlbfalcao/jruby"
mod "puppetlabs/java"


# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
